use casperstay_db;

DROP TABLE IF EXISTS BOOKING;
DROP TABLE IF EXISTS HOTEL;

DROP TABLE IF EXISTS USER;
CREATE TABLE USER(
  USER_EMAIL varchar(50) NOT NULL PRIMARY KEY,
  USER_NAME varchar(50),
  USER_PHONE varchar(50),
  USER_PASSWORD varchar(50)
)
ENGINE=INNODB DEFAULT CHARSET = latin1;


DROP TABLE IF EXISTS HOTEL_ROOM_DETAILS;
CREATE TABLE HOTEL_ROOM_DETAILS(
  ROOM_ID INT(11) PRIMARY KEY,
  ROOM_TYPE VARCHAR(50),
  ROOM_PRICE INT(11),
  HOTEL_ID INT(11)
)
ENGINE=INNODB DEFAULT CHARSET = latin1;

INSERT INTO HOTEL_ROOM_DETAILS VALUES(1001,'Double Room AC',10000,1);
INSERT INTO HOTEL_ROOM_DETAILS VALUES(1002,'Double Room Non-AC',5000,2);
INSERT INTO HOTEL_ROOM_DETAILS VALUES(1003,'Double Room Non-AC',5000,2);
INSERT INTO HOTEL_ROOM_DETAILS VALUES(1004,'Single Room Non-AC',3000,2);
INSERT INTO HOTEL_ROOM_DETAILS VALUES(1005,'Single Room AC',2000,1);

DROP PROCEDURE IF EXISTS DELETE_BOOKING;
DELIMITER //
CREATE PROCEDURE DELETE_BOOKING(IN b_id INT)
BEGIN
  DELETE FROM BOOKING WHERE BOOKING_ID=b_id;
  SELECT "Booking Deleted Succesfully..." AS SUCCESS;
END;
// DELIMITER ;


DROP PROCEDURE IF EXISTS FETCH_ROOM_PRICE;
DELIMITER //
CREATE PROCEDURE FETCH_ROOM_PRICE(IN r_id INT, OUT r_price INT)
BEGIN
  SELECT ROOM_PRICE INTO r_price FROM HOTEL_ROOM_DETAILS WHERE ROOM_ID=r_id;
END;
// DELIMITER ;

-- CALL FETCH_ROOM_PRICE(1002, @result);
-- SELECT @result;


-- UPDATE USER PROFILE
DROP PROCEDURE IF EXISTS UPDATE_PROFILE;
DELIMITER //
CREATE PROCEDURE UPDATE_PROFILE(v_phone VARCHAR(20),v_password VARCHAR(20), v_name VARCHAR(30), v_email VARCHAR(30), OUT success INT)
BEGIN
  
  DECLARE v_out INT DEFAULT 0;
  DECLARE v_check_user INT DEFAULT 0;
  SET SESSION SQL_SAFE_UPDATES = 0;
  SELECT COUNT(*) INTO v_check_user FROM USER WHERE USER_EMAIL=v_email;
  IF v_check_user = 1 THEN
    UPDATE USER 
      SET USER_PHONE = v_phone,  
            USER_NAME = v_name, 
            USER_PASSWORD = v_password
        WHERE USER_EMAIL = v_email;
      SET success = 1;
  ELSE
      SET success = 0;
  END IF;
  SET SESSION SQL_SAFE_UPDATES = 1;
END;
// DELIMITER ;

-- CALL UPDATE_PROFILE('555-0101', '123ABC', 'MARK', 'alex.smith@example.com', @v_out);

-- STORED FUNCTIONS
DROP FUNCTION IF EXISTS CALCULATE_ROOM_PRICE;
DELIMITER //

CREATE FUNCTION CALCULATE_ROOM_PRICE ( 
    check_in DATE, 
    check_out DATE, 
    no_of_rooms INT, 
    h_id INT, 
    r_type VARCHAR(20)
)
RETURNS FLOAT
READS SQL DATA -- This fixes Error 1418
DETERMINISTIC  -- Good practice for functions with the same inputs/outputs
BEGIN
    DECLARE total_price FLOAT DEFAULT 0.0;
    DECLARE room_price_per_day FLOAT DEFAULT 0.0;
    DECLARE days INT DEFAULT 0;

    SET days = ABS(DATEDIFF(check_in, check_out));
    
    IF days = 0 THEN
      RETURN -1;
    ELSE
      -- Fetch the price from the table
      SELECT ROOM_PRICE INTO room_price_per_day 
      FROM HOTEL_ROOM_DETAILS 
      WHERE HOTEL_ID = h_id AND ROOM_TYPE = r_type;
      
      SET total_price = room_price_per_day * days * no_of_rooms;
    END IF;

    RETURN total_price;
END;
//
DELIMITER ;


-- SELECT CALCULATE_ROOM_PRICE('2020-08-07','2020-08-09',1,1,'Double Room AC')